# Generated by Django 4.2 on 2025-10-10 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedModel',
            fields=[
                ('color', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('first_model_id_ns', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'main_aggregatedmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CleanReportsBuy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('editor', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(max_length=40)),
                ('model_id_ns', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('color', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='Not', max_length=20)),
                ('invoice_id', models.IntegerField(default=0)),
                ('date_bought', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_distributed', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_rdy_for_ship', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_shipped', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_rdy_for_close', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'main_cleanreportsbuy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyNew',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('code', models.CharField(max_length=40)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'main_currencynew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(db_column='customer_id', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InnerCompanys',
            fields=[
                ('company_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_innercompanys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=70, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('price_per_unit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_invoicecontent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('created_date', models.DateField()),
                ('invoice', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('real_number', models.CharField(blank=True, max_length=40, null=True)),
                ('inner_number', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('rate_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'main_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricesClean',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.CharField(default='None', max_length=50)),
                ('country', models.CharField(default='None', max_length=50)),
                ('model', models.CharField(default='None', max_length=50)),
                ('color', models.CharField(default='None', max_length=40)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'main_pricesclean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecsDetail',
            fields=[
                ('country_short', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('spec', models.CharField(blank=True, max_length=50, null=True)),
                ('iso_alpha', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'main_specsdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('sponsor_id', models.CharField(db_column='sponsor_id', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_sponsors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('model_type', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_taxrates',
                'managed': False,
            },
        ),
    ]
