# Generated by Django 4.2 on 2025-10-10 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('sim_spec', models.CharField(choices=[('SIM+SIM', 'Сим+Сим'), ('ESIM', 'ЕСим'), ('SIM+ESIM', 'Сим+ЕСим')], default='SIM+SIM', max_length=10)),
                ('order_qty', models.IntegerField()),
                ('partner_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partner_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stat_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stat_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOffersActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_edited', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='dashboards.tendercontent')),
            ],
        ),
    ]
