# Generated by Django 4.2 on 2025-10-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_tendercontent_partneroffersactions_partneroffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferWinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='dashboards.partneroffers')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='dashboards.tendercontent')),
            ],
        ),
    ]
