# Generated by Django 4.2 on 2025-10-14 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_offerwinners'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendercontent',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
