# Generated by Django 4.2 on 2025-10-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_tendercontent_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendercontent',
            name='buyer_name',
            field=models.CharField(default='unknown'),
        ),
    ]
