# Generated by Django 4.2 on 2025-10-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_tendercontent_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneroffersactions',
            name='new_value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='partneroffersactions',
            name='old_value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='partneroffersactions',
            name='target',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
