# Generated by Django 4.2 on 2025-10-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_partneroffersactions_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneroffersactions',
            name='action',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='partneroffersactions',
            name='target',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
