# Generated by Django 4.2 on 2025-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_partneroffersactions_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneroffersactions',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
