# Generated by Django 4.2 on 2025-10-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_partneroffersactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendercontent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
    ]
