# Generated by Django 4.2 on 2025-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_tendercontent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendercontent',
            name='finish_reason',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
