# Generated by Django 4.2 on 2025-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_tendercontent_finish_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneroffers',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
